name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a timeout to avoid hanging builds
    strategy:
      matrix:
        python-version: [3.9]  # Start with just one version for simplicity

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        
    - name: Install minimal dependencies
      run: |
        # Install only the essential dependencies to run tests
        pip install pyyaml python-dateutil colorama
        
    - name: Install package in development mode
      run: |
        pip install -e .
        
    - name: Run linting checks
      run: |
        # Check for syntax errors only
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run basic tests
      run: |
        pytest tests/test_basic_imports.py -v
